# TCL File Generated by Component Editor 18.1
# Tue Dec 30 13:06:58 CET 2025
# DO NOT MODIFY


# 
# rgb_framebuffer "RGB Framebuffer Controller" v1.0
#  2025.12.30.13:06:58
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rgb_framebuffer
# 
set_module_property DESCRIPTION ""
set_module_property NAME rgb_framebuffer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "RGB Framebuffer Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rgb_framebuffer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file rgb_framebuffer.vhdl VHDL PATH rgb_framebuffer.vhdl TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_sink_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_sink_reset reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avalon_slave_address address Input 10
add_interface_port avalon_slave avalon_slave_read read Input 1
add_interface_port avalon_slave avalon_slave_write write Input 1
add_interface_port avalon_slave avalon_slave_writedata writedata Input 32
add_interface_port avalon_slave avalon_slave_readdata readdata Output 32
add_interface_port avalon_slave avalon_slave_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rgb_matrix_conduit
# 
add_interface rgb_matrix_conduit conduit end
set_interface_property rgb_matrix_conduit associatedClock clock_sink
set_interface_property rgb_matrix_conduit associatedReset ""
set_interface_property rgb_matrix_conduit ENABLED true
set_interface_property rgb_matrix_conduit EXPORT_OF ""
set_interface_property rgb_matrix_conduit PORT_NAME_MAP ""
set_interface_property rgb_matrix_conduit CMSIS_SVD_VARIABLES ""
set_interface_property rgb_matrix_conduit SVD_ADDRESS_GROUP ""

add_interface_port rgb_matrix_conduit matrix_r1 r1 Output 1
add_interface_port rgb_matrix_conduit matrix_g1 g1 Output 1
add_interface_port rgb_matrix_conduit matrix_b1 b1 Output 1
add_interface_port rgb_matrix_conduit matrix_r2 r2 Output 1
add_interface_port rgb_matrix_conduit matrix_g2 g2 Output 1
add_interface_port rgb_matrix_conduit matrix_b2 b2 Output 1
add_interface_port rgb_matrix_conduit matrix_addr_a addr_a Output 1
add_interface_port rgb_matrix_conduit matrix_addr_b addr_b Output 1
add_interface_port rgb_matrix_conduit matrix_addr_c addr_c Output 1
add_interface_port rgb_matrix_conduit matrix_clk clk_out Output 1
add_interface_port rgb_matrix_conduit matrix_lat lat Output 1
add_interface_port rgb_matrix_conduit matrix_oe_n oe_n Output 1

